### ISSUE TITLE
Recursive options

### ISSUE THREAD

**Issue by salomao-rodrigues** [chilts/12factor-config#2]
Any plans on having multiple levels of options?

So that we could have something like:

``` javascript
storage: {
    driver: {
      env: 'STORAGE_DRIVER',...
    },
    host: {
      env: 'STORAGE_HOST',...
    }
}
```

I could try and submit a PR if I find the time.

**Comment by chilts** [comment]
I don't really have plans for this. Since the environment is a flat data structure, I figured I'd just keep a flat one being returned too. :)

I'm not against hierarchical/multiple level options but the current `index.js` is 89 lines, so I'd only probably be happy to merge it if it didn't add much more complexity. If that sounds doable, go ahead. More tests with any PR would be awesome.

**Comment by chilts** [comment]
Thanks for closing. :)

**Comment by salomao-rodrigues** [comment]
You're very welcome, sorry for not having replied in the meanwhile!
What you've said does make sense, thank's for creating the module.
I'm using it :)

**Comment by chilts** [comment]
Following on from #8, I've decided that we will keep the hierarchy flat for this package. If anyone really needs a hierarchical config, feel free to fork this repo and publish a version of it. I'm happy if someone requires this, however, I'm going to keep this one as-is at the moment - flat. :)
